# Generated by Django 3.1.7 on 2021-03-16 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plotter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=150, unique=True, verbose_name='Serial Number')),
                ('ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('cutouts', models.IntegerField(default=0, verbose_name='Allowed cutouts')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
