# Generated by Django 3.1.7 on 2021-03-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='Serial Number',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
