# Generated by Django 3.1.7 on 2021-03-10 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotter',
            name='Serial Number',
        ),
        migrations.AddField(
            model_name='plotter',
            name='serial_number',
            field=models.CharField(default='', max_length=150, verbose_name='Serial Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plotter',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
