# Generated by Django 3.1.7 on 2021-03-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0002_auto_20210310_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='serial_number',
            field=models.CharField(max_length=150, unique=True, verbose_name='Serial Number'),
        ),
    ]
