# Generated by Django 3.1.7 on 2021-03-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0004_remove_plotter_serial_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plotter',
        ),
    ]
