# Generated by Django 3.1.7 on 2021-03-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0006_plotter'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
