# Generated by Django 3.1.7 on 2021-03-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0007_plotter_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='cutouts',
            field=models.IntegerField(default=0),
        ),
    ]
