# Generated by Django 3.1.7 on 2021-03-12 10:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mold', '__first__'),
        ('plotter', '0006_plotter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 3, 12, 13, 40, 6, 53792))),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mold', to='mold.mold')),
                ('plotter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plotter', to='plotter.plotter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
