# Generated by Django 3.1.7 on 2021-03-12 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutout',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 13, 45, 25, 192296)),
        ),
    ]
