# Generated by Django 3.1.7 on 2021-03-14 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotterstatistics',
            name='last_cutout_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
