# Generated by Django 3.1.7 on 2021-03-12 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20210312_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutout',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 13, 50, 48, 97601)),
        ),
    ]
