# Generated by Django 3.1.7 on 2021-03-14 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_plotterstatistics_last_cutout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotterstatistics',
            name='last_cutout_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
